on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # your build step here
        
      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@v1.0.0
        with:
          nekoweb-username: "thepersonever"
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
          nekoweb-domain: 'thepersonever.net'
          directory: 'tpe'

